### ISSUE TITLE
running error about ade20k 

### ISSUE THREAD

**Issue by lulu9449** [microsoft/CoCosNet#30]
I want to repeat the training mission of mask to image.

I moved images named ADE_train_*.png and ADE_val_*.png to  the destination folder and use the following command to do this.

CUDA_VISIBLE_DEVICES=0,1 python train.py --name ade20k --dataset_mode ade20k --dataroot /data/ADE20K_2016_07_26/images --niter 100 --niter_decay 100 --use_attention --maskmix --warp_mask_losstype direct --weight_mask 100.0 --PONO --PONO_C --batchSize 4 --vgg_normal_correct --gpu_ids 0,1

then the following error was reported

AssertionError: The label-image pair (/data/ADE20K_2016_07_26/images/training/a/airport/airport/ADE_train_00001069_parts_1.png, /data/ADE20K_2016_07_26/images/training/a/airport/airport/ADE_train_00001069.jpg) do not look like the right pair because the filenames are quite different. Are you sure about the pairing? Please see data/pix2pix_dataset.py to see what is going on, and use --no_pairing_check to bypass this.

I noticed that all of the images in ADE20K are RGB images, so how do you transfer them into gray images? The images located in CoCosNet/imgs/ade20k/training/ in your project are pairs of a RGB image and a gray image.

waiting for your reply

**Comment by panzhang0104** [comment]
1. The AssertionError is caused by the pairing_check function, this function checks whether the pair images have the same names (in your case: ADE_train_00001069_parts_1 != ADE_train_00001069). So, please use --no_pairing_check to avoid this error.
2. The mask of ADE20k has three representations, RGB mask: class color, Gray mask: class index, Onehot mask: onehot representation of class index. Please refer to the [issue](https://github.com/CSAILVision/semantic-segmentation-pytorch/issues/7) for more detail.  We use onehot representation as the input.
